# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Sean Massa's Blog"
description: ""

email: endangeredmassa@gmail.com
logo: "/assets/images/logo.svg"
float_logo: true

# blog cover
# cover:

name: "Sean Massa"
author: "Sean Massa"
author_image: "/assets/images/author.jpg"

permalink: /blog/:categories/:title
paginate:	10

url: "http://massalabs.com" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@endangeredmassa'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/endangeredmassa
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	mastodon
    url:	https://social.massalabs.com/@sean
    desc: Follow me on mastodon

  - icon:	github
    url:	https://github.com/endangeredmassa
    desc:	Fork me on github
